GLOBAL_SKILL_VECTOR = [
    '.NET',
    'AWS',
    'AWS EC2',
    'AWS Lambda',
    'AWS RDS',
    'AWS S3',
    'Airflow',
    'Angular',
    'Ansible',
    'Apache Spark',
    'ArgoCD',
    'Avro',
    'Azure',
    'Azure DevOps',
    'Azure Functions',
    'Bash',
    'BigQuery',
    'Blue-Green Deployment',
    'C#',
    'C++',
    'CI/CD',
    'CSS',
    'Canary Releases',
    'Cloud Networking',
    'CloudFormation',
    'Computer Vision',
    'Django',
    'Distributed Systems',
    'Docker',
    'Docker Compose',
    'ELK Stack',
    'ELT',
    'ETL',
    'Express.js',
    'FastAPI',
    'Feature Engineering',
    'Figma',
    'Flask',
    'GitHub Actions',
    'GitLab CI',
    'GitOps',
    'Go',
    'Google Cloud',
    'Grafana',
    'Hadoop',
    'HTML',
    'Hugging Face',
    'Java',
    'Jenkins',
    'Jupyter Notebook',
    'Kafka',
    'Keras',
    'Kubernetes',
    'LLMs',
    'Linux',
    'Load Balancing',
    'Machine Learning',
    'MATLAB',
    'MLflow',
    'MLOps',
    'NLP',
    'Nginx',
    'Node.js',
    'NumPy',
    'OOP',
    'OLAP Cubes',
    'ONNX',
    'Pandas',
    'Parquet',
    'Performance Engineering',
    'PostgreSQL',
    'Prometheus',
    'PyTorch',
    'Python',
    'R',
    'React',
    'Redshift',
    'Redis',
    'Scikit-learn',
    'Seaborn',
    'Security Hardening',
    'Selenium',
    'Snowflake',
    'SOLID Principles',
    'SQL',
    'Spark',
    'Spring',
    'Star Schema',
    'TensorFlow',
    'Terraform',
    'Time Series Forecasting',
    'Transformers',
    'TypeScript',
    'Vue.js',
    'Git',
    'GitHub',
    'Jira',
    'MySQL',
    'MongoDB',
    'REST APIs',
]